
ALTER TABLE public.opportunities
  ADD COLUMN IF NOT EXISTS target_covered_sqm numeric,
  ADD COLUMN IF NOT EXISTS target_covered_sqm_max numeric,
  ADD COLUMN IF NOT EXISTS target_yard_sqm numeric,
  ADD COLUMN IF NOT EXISTS target_internal_height numeric,
  ADD COLUMN IF NOT EXISTS target_truck_access boolean,
  ADD COLUMN IF NOT EXISTS target_near_highway boolean,
  ADD COLUMN IF NOT EXISTS target_near_port boolean,
  ADD COLUMN IF NOT EXISTS target_intended_use text,
  ADD COLUMN IF NOT EXISTS target_zone text,
  ADD COLUMN IF NOT EXISTS target_notes text,
  ADD COLUMN IF NOT EXISTS measured_covered_sqm numeric,
  ADD COLUMN IF NOT EXISTS measured_yard_sqm numeric,
  ADD COLUMN IF NOT EXISTS measured_length numeric,
  ADD COLUMN IF NOT EXISTS measured_width numeric,
  ADD COLUMN IF NOT EXISTS measurement_source text,
  ADD COLUMN IF NOT EXISTS measurement_confidence text,
  ADD COLUMN IF NOT EXISTS measurement_notes text,
  ADD COLUMN IF NOT EXISTS geometry_data jsonb,
  ADD COLUMN IF NOT EXISTS geojson_data jsonb,
  ADD COLUMN IF NOT EXISTS kml_file_url text,
  ADD COLUMN IF NOT EXISTS compatibility_status text,
  ADD COLUMN IF NOT EXISTS compatibility_score integer,
  ADD COLUMN IF NOT EXISTS missing_data jsonb,
  ADD COLUMN IF NOT EXISTS suggested_next_action text,
  ADD COLUMN IF NOT EXISTS last_measured_at timestamptz;
